modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "0.8"
displayName = "Perimeter"
authors = "Tesmio"
description = '''A minecraft mod that adds a large number of blocks to protect your property on your own. Sensors, walls, fences, alarm blocks, and more.'''
logoFile = "assets/perimeter/logo.png"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"